(ns net.wikipunk.rdf.ergast
  "OWL ontology generated by the xsd2owl XML Style Sheet (http://rhizomik.net/redefer)"
  {:rdf/ns-prefix-map
   {"ergast"
    "https://redefer.rhizomik.net/xsd2owl?xsd=https://ergast.com/schemas/mrd-1.4.xsd#",
    "mrd" "#",
    "owl" "http://www.w3.org/2002/07/owl#",
    "rdf" "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs" "http://www.w3.org/2000/01/rdf-schema#",
    "xo" "http://rhizomik.net/redefer/xsl/xsd2owl-functions.xsl",
    "xsd" "http://www.w3.org/2001/XMLSchema"},
   :rdf/type :owl/Ontology,
   :rdfa/prefix "ergast",
   :rdfa/uri
   "https://redefer.rhizomik.net/xsd2owl?xsd=https://ergast.com/schemas/mrd-1.4.xsd",
   :rdfs/comment
   "OWL ontology generated by the xsd2owl XML Style Sheet (http://rhizomik.net/redefer)"}
  (:refer-clojure :exclude [count long time]))

(def AverageSpeed
  {:db/ident :ergast/AverageSpeed,
   :rdf/type :owl/ObjectProperty})

(def Circuit
  {:db/ident :ergast/Circuit,
   :rdf/type :owl/ObjectProperty})

(def CircuitIdRef
  {:db/ident :ergast/CircuitIdRef,
   :rdf/type :owl/DatatypeProperty})

(def CircuitName
  {:db/ident :ergast/CircuitName,
   :rdf/type :owl/DatatypeProperty})

(def CircuitTable
  {:db/ident :ergast/CircuitTable,
   :rdf/type :owl/ObjectProperty})

(def CircuitTableType
  {:db/ident        :ergast/CircuitTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/CircuitType,
                                            :owl/onProperty :ergast/Circuit,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def CircuitType
  {:db/ident        :ergast/CircuitType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/url,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/circuitId,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/circuitId,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf [{:owl/allValuesFrom :xsd/string,
                                            :owl/onProperty :ergast/CircuitName,
                                            :rdf/type :owl/Restriction}
                                           {:owl/minCardinality 1,
                                            :owl/onProperty :ergast/CircuitName,
                                            :rdf/type :owl/Restriction}
                                           {:owl/maxCardinality 1,
                                            :owl/onProperty :ergast/CircuitName,
                                            :rdf/type :owl/Restriction}
                                           {:owl/allValuesFrom
                                            :ergast/LocationType,
                                            :owl/onProperty :ergast/Location,
                                            :rdf/type :owl/Restriction}
                                           {:owl/minCardinality 1,
                                            :owl/onProperty :ergast/Location,
                                            :rdf/type :owl/Restriction}
                                           {:owl/maxCardinality 1,
                                            :owl/onProperty :ergast/Location,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def Constructor
  {:db/ident :ergast/Constructor,
   :rdf/type :owl/ObjectProperty})

(def ConstructorIdRef
  {:db/ident :ergast/ConstructorIdRef,
   :rdf/type :owl/DatatypeProperty})

(def ConstructorStanding
  {:db/ident :ergast/ConstructorStanding,
   :rdf/type :owl/ObjectProperty})

(def ConstructorStandingType
  {:db/ident :ergast/ConstructorStandingType,
   :rdf/type :owl/Class,
   :rdfs/subClassOf [{:owl/minCardinality 1,
                      :owl/onProperty     :ergast/wins,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/wins,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/points,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/float,
                      :owl/onProperty    :ergast/points,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/position,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/position,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/unionOf [{:owl/allValuesFrom
                                       :ergast/ConstructorType,
                                       :owl/onProperty :ergast/Constructor,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}],
                        :rdf/type    :owl/Class}],
                      :rdf/type :owl/Class}]})

(def ConstructorTable
  {:db/ident :ergast/ConstructorTable,
   :rdf/type :owl/ObjectProperty})

(def ConstructorTableType
  {:db/ident        :ergast/ConstructorTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/ConstructorType,
                                            :owl/onProperty :ergast/Constructor,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def ConstructorType
  {:db/ident        :ergast/ConstructorType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/url,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/constructorId,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/constructorId,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf [{:owl/allValuesFrom :xsd/string,
                                            :owl/onProperty    :ergast/Name,
                                            :rdf/type          :owl/Restriction}
                                           {:owl/minCardinality 1,
                                            :owl/onProperty :ergast/Name,
                                            :rdf/type :owl/Restriction}
                                           {:owl/maxCardinality 1,
                                            :owl/onProperty :ergast/Name,
                                            :rdf/type :owl/Restriction}
                                           {:owl/allValuesFrom :xsd/string,
                                            :owl/onProperty :ergast/Nationality,
                                            :rdf/type :owl/Restriction}
                                           {:owl/maxCardinality 1,
                                            :owl/onProperty :ergast/Nationality,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def Country
  {:db/ident :ergast/Country,
   :rdf/type :owl/DatatypeProperty})

(def Date
  {:db/ident :ergast/Date,
   :rdf/type :owl/DatatypeProperty})

(def DateOfBirth
  {:db/ident :ergast/DateOfBirth,
   :rdf/type :owl/DatatypeProperty})

(def Driver
  {:db/ident :ergast/Driver,
   :rdf/type :owl/ObjectProperty})

(def DriverIdRef
  {:db/ident :ergast/DriverIdRef,
   :rdf/type :owl/DatatypeProperty})

(def DriverStanding
  {:db/ident :ergast/DriverStanding,
   :rdf/type :owl/ObjectProperty})

(def DriverStandingType
  {:db/ident        :ergast/DriverStandingType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/minCardinality 1,
                      :owl/onProperty     :ergast/wins,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/wins,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/points,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/float,
                      :owl/onProperty    :ergast/points,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/position,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/position,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/unionOf [{:owl/allValuesFrom :ergast/DriverType,
                                       :owl/onProperty    :ergast/Driver,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Driver,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/Driver,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty    :ergast/DriverIdRef,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/DriverIdRef,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/DriverIdRef,
                                       :rdf/type           :owl/Restriction}],
                        :rdf/type    :owl/Class}
                       {:owl/unionOf [{:owl/allValuesFrom
                                       :ergast/ConstructorType,
                                       :owl/onProperty :ergast/Constructor,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}],
                        :rdf/type    :owl/Class}],
                      :rdf/type :owl/Class}]})

(def DriverTable
  {:db/ident :ergast/DriverTable,
   :rdf/type :owl/ObjectProperty})

(def DriverTableType
  {:db/ident        :ergast/DriverTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/DriverType,
                                            :owl/onProperty :ergast/Driver,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def DriverType
  {:db/ident        :ergast/DriverType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/url,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/driverId,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/driverId,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/allValuesFrom :xsd/integer,
                        :owl/onProperty    :ergast/PermanentNumber,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/PermanentNumber,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :xsd/string,
                        :owl/onProperty    :ergast/GivenName,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/GivenName,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/GivenName,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :xsd/string,
                        :owl/onProperty    :ergast/FamilyName,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/FamilyName,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/FamilyName,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :xsd/date,
                        :owl/onProperty    :ergast/DateOfBirth,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/DateOfBirth,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :xsd/string,
                        :owl/onProperty    :ergast/Nationality,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Nationality,
                        :rdf/type           :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def DurationType
  {:db/ident        :ergast/DurationType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/allValuesFrom :xsd/integer,
                     :owl/onProperty    :ergast/millis,
                     :rdf/type          :owl/Restriction}})

(def FamilyName
  {:db/ident :ergast/FamilyName,
   :rdf/type :owl/DatatypeProperty})

(def FastestLap
  {:db/ident :ergast/FastestLap,
   :rdf/type :owl/ObjectProperty})

(def FastestLapType
  {:db/ident :ergast/FastestLapType,
   :rdf/type :owl/Class,
   :rdfs/subClassOf [{:owl/minCardinality 1,
                      :owl/onProperty     :ergast/lap,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/lap,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/rank,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/rank,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/allValuesFrom :ergast/DurationType,
                        :owl/onProperty    :ergast/Time,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Time,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Time,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/SpeedType,
                        :owl/onProperty    :ergast/AverageSpeed,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/AverageSpeed,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/AverageSpeed,
                        :rdf/type           :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def GivenName
  {:db/ident :ergast/GivenName,
   :rdf/type :owl/DatatypeProperty})

(def Grid
  {:db/ident :ergast/Grid,
   :rdf/type :owl/DatatypeProperty})

(def Lap
  {:db/ident :ergast/Lap,
   :rdf/type :owl/ObjectProperty})

(def LapType
  {:db/ident        :ergast/LapType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/minCardinality 1,
                      :owl/onProperty     :ergast/number,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/number,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/TimingType,
                                            :owl/onProperty :ergast/Timing,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def Laps
  {:db/ident :ergast/Laps,
   :rdf/type :owl/DatatypeProperty})

(def LapsList
  {:db/ident :ergast/LapsList,
   :rdf/type :owl/ObjectProperty})

(def LapsListType
  {:db/ident        :ergast/LapsListType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/intersectionOf [{:owl/allValuesFrom :ergast/LapType,
                                           :owl/onProperty :ergast/Lap,
                                           :rdf/type :owl/Restriction}],
                     :rdf/type :owl/Class}})

(def Locality
  {:db/ident :ergast/Locality,
   :rdf/type :owl/DatatypeProperty})

(def Location
  {:db/ident :ergast/Location,
   :rdf/type :owl/ObjectProperty})

(def LocationType
  {:db/ident        :ergast/LocationType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/int,
                      :owl/onProperty    :ergast/alt,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/float,
                      :owl/onProperty    :ergast/long,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/float,
                      :owl/onProperty    :ergast/lat,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf [{:owl/allValuesFrom :xsd/string,
                                            :owl/onProperty    :ergast/Locality,
                                            :rdf/type          :owl/Restriction}
                                           {:owl/minCardinality 1,
                                            :owl/onProperty :ergast/Locality,
                                            :rdf/type :owl/Restriction}
                                           {:owl/allValuesFrom :xsd/string,
                                            :owl/onProperty    :ergast/Country,
                                            :rdf/type          :owl/Restriction}
                                           {:owl/minCardinality 1,
                                            :owl/onProperty :ergast/Country,
                                            :rdf/type :owl/Restriction}
                                           {:owl/maxCardinality 1,
                                            :owl/onProperty :ergast/Country,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def MRData
  {:db/ident   :ergast/MRData,
   :rdf/type   :owl/ObjectProperty,
   :rdfs/range :ergast/MRDataType})

(def MRDataType
  {:db/ident        :ergast/MRDataType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/total,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/offset,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/limit,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/url,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/series,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/allValuesFrom :ergast/SeasonTableType,
                        :owl/onProperty    :ergast/SeasonTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/SeasonTable,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/RaceTableType,
                        :owl/onProperty    :ergast/RaceTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/RaceTable,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/StandingsTableType,
                        :owl/onProperty    :ergast/StandingsTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/StandingsTable,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/DriverTableType,
                        :owl/onProperty    :ergast/DriverTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/DriverTable,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/ConstructorTableType,
                        :owl/onProperty    :ergast/ConstructorTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/ConstructorTable,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/CircuitTableType,
                        :owl/onProperty    :ergast/CircuitTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/CircuitTable,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/StatusTableType,
                        :owl/onProperty    :ergast/StatusTable,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/StatusTable,
                        :rdf/type           :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def Name
  {:db/ident :ergast/Name,
   :rdf/type :owl/DatatypeProperty})

(def Nationality
  {:db/ident :ergast/Nationality,
   :rdf/type :owl/DatatypeProperty})

(def PermanentNumber
  {:db/ident :ergast/PermanentNumber,
   :rdf/type :owl/DatatypeProperty})

(def PitStop
  {:db/ident :ergast/PitStop,
   :rdf/type :owl/ObjectProperty})

(def PitStopType
  {:db/ident        :ergast/PitStopType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/duration,
                      :owl/onProperty    :ergast/duration,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/time,
                      :owl/onProperty    :ergast/time,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/lap,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/lap,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/stop,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/stop,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/driverId,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/driverId,
                      :rdf/type          :owl/Restriction}]})

(def PitStopsList
  {:db/ident :ergast/PitStopsList,
   :rdf/type :owl/ObjectProperty})

(def PitStopsListType
  {:db/ident        :ergast/PitStopsListType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/intersectionOf [{:owl/allValuesFrom
                                           :ergast/PitStopType,
                                           :owl/onProperty :ergast/PitStop,
                                           :rdf/type :owl/Restriction}],
                     :rdf/type :owl/Class}})

(def Q1
  {:db/ident :ergast/Q1,
   :rdf/type :owl/ObjectProperty})

(def Q2
  {:db/ident :ergast/Q2,
   :rdf/type :owl/ObjectProperty})

(def Q3
  {:db/ident :ergast/Q3,
   :rdf/type :owl/ObjectProperty})

(def QualifyingList
  {:db/ident :ergast/QualifyingList,
   :rdf/type :owl/ObjectProperty})

(def QualifyingListType
  {:db/ident        :ergast/QualifyingListType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/intersectionOf [{:owl/allValuesFrom
                                           :ergast/QualifyingResultType,
                                           :owl/onProperty
                                           :ergast/QualifyingResult,
                                           :rdf/type :owl/Restriction}],
                     :rdf/type :owl/Class}})

(def QualifyingResult
  {:db/ident :ergast/QualifyingResult,
   :rdf/type :owl/ObjectProperty})

(def QualifyingResultType
  {:db/ident        :ergast/QualifyingResultType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/minCardinality 1,
                      :owl/onProperty     :ergast/position,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/position,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/number,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/unionOf [{:owl/allValuesFrom :ergast/DriverType,
                                       :owl/onProperty    :ergast/Driver,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Driver,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/Driver,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty    :ergast/DriverIdRef,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/DriverIdRef,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/DriverIdRef,
                                       :rdf/type           :owl/Restriction}],
                        :rdf/type    :owl/Class}
                       {:owl/unionOf [{:owl/allValuesFrom
                                       :ergast/ConstructorType,
                                       :owl/onProperty :ergast/Constructor,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}],
                        :rdf/type    :owl/Class}
                       {:owl/allValuesFrom :ergast/DurationType,
                        :owl/onProperty    :ergast/Q1,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Q1,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Q1,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/DurationType,
                        :owl/onProperty    :ergast/Q2,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Q2,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/DurationType,
                        :owl/onProperty    :ergast/Q3,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Q3,
                        :rdf/type           :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def Race
  {:db/ident :ergast/Race,
   :rdf/type :owl/ObjectProperty})

(def RaceName
  {:db/ident :ergast/RaceName,
   :rdf/type :owl/DatatypeProperty})

(def RaceTable
  {:db/ident :ergast/RaceTable,
   :rdf/type :owl/ObjectProperty})

(def RaceTableType
  {:db/ident        :ergast/RaceTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom :ergast/RaceType,
                                            :owl/onProperty :ergast/Race,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def RaceType
  {:db/ident        :ergast/RaceType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/url,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/round,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/round,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/season,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/season,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/allValuesFrom :xsd/string,
                        :owl/onProperty    :ergast/RaceName,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/RaceName,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/RaceName,
                        :rdf/type           :owl/Restriction}
                       {:owl/unionOf [{:owl/allValuesFrom :ergast/CircuitType,
                                       :owl/onProperty    :ergast/Circuit,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Circuit,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/Circuit,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty    :ergast/CircuitIdRef,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/CircuitIdRef,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/CircuitIdRef,
                                       :rdf/type           :owl/Restriction}],
                        :rdf/type    :owl/Class}
                       {:owl/allValuesFrom :xsd/date,
                        :owl/onProperty    :ergast/Date,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Date,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Date,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :xsd/time,
                        :owl/onProperty    :ergast/Time,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Time,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Time,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/QualifyingListType,
                        :owl/onProperty    :ergast/QualifyingList,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/QualifyingList,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/ResultsListType,
                        :owl/onProperty    :ergast/ResultsList,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/ResultsList,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/LapsListType,
                        :owl/onProperty    :ergast/LapsList,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/LapsList,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/PitStopsListType,
                        :owl/onProperty    :ergast/PitStopsList,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/PitStopsList,
                        :rdf/type           :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def Result
  {:db/ident :ergast/Result,
   :rdf/type :owl/ObjectProperty})

(def ResultType
  {:db/ident        :ergast/ResultType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/float,
                      :owl/onProperty    :ergast/points,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/position,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/position,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/number,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf
                      [{:owl/unionOf [{:owl/allValuesFrom :ergast/DriverType,
                                       :owl/onProperty    :ergast/Driver,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Driver,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty    :ergast/DriverIdRef,
                                       :rdf/type          :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/DriverIdRef,
                                       :rdf/type           :owl/Restriction}],
                        :rdf/type    :owl/Class}
                       {:owl/unionOf [{:owl/allValuesFrom
                                       :ergast/ConstructorType,
                                       :owl/onProperty :ergast/Constructor,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty     :ergast/Constructor,
                                       :rdf/type           :owl/Restriction}
                                      {:owl/allValuesFrom :xsd/string,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/minCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}
                                      {:owl/maxCardinality 1,
                                       :owl/onProperty :ergast/ConstructorIdRef,
                                       :rdf/type :owl/Restriction}],
                        :rdf/type    :owl/Class}
                       {:owl/allValuesFrom :xsd/integer,
                        :owl/onProperty    :ergast/Grid,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Grid,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Grid,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :xsd/integer,
                        :owl/onProperty    :ergast/Laps,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Laps,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Laps,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/StatusType,
                        :owl/onProperty    :ergast/Status,
                        :rdf/type          :owl/Restriction}
                       {:owl/minCardinality 1,
                        :owl/onProperty     :ergast/Status,
                        :rdf/type           :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Status,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/DurationType,
                        :owl/onProperty    :ergast/Time,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/Time,
                        :rdf/type           :owl/Restriction}
                       {:owl/allValuesFrom :ergast/FastestLapType,
                        :owl/onProperty    :ergast/FastestLap,
                        :rdf/type          :owl/Restriction}
                       {:owl/maxCardinality 1,
                        :owl/onProperty     :ergast/FastestLap,
                        :rdf/type           :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def ResultsList
  {:db/ident :ergast/ResultsList,
   :rdf/type :owl/ObjectProperty})

(def ResultsListType
  {:db/ident        :ergast/ResultsListType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/intersectionOf [{:owl/allValuesFrom
                                           :ergast/ResultType,
                                           :owl/onProperty :ergast/Result,
                                           :rdf/type :owl/Restriction}],
                     :rdf/type :owl/Class}})

(def Season
  {:db/ident :ergast/Season,
   :rdf/type :owl/ObjectProperty})

(def SeasonTable
  {:db/ident :ergast/SeasonTable,
   :rdf/type :owl/ObjectProperty})

(def SeasonTableType
  {:db/ident        :ergast/SeasonTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/SeasonType,
                                            :owl/onProperty :ergast/Season,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def SeasonType
  {:db/ident        :ergast/SeasonType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/allValuesFrom :xsd/string,
                     :owl/onProperty    :ergast/url,
                     :rdf/type          :owl/Restriction}})

(def SpeedType
  {:db/ident        :ergast/SpeedType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf {:owl/allValuesFrom :xsd/string,
                     :owl/onProperty    :ergast/units,
                     :rdf/type          :owl/Restriction}})

(def StandingsList
  {:db/ident :ergast/StandingsList,
   :rdf/type :owl/ObjectProperty})

(def StandingsListType
  {:db/ident        :ergast/StandingsListType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/round,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/season,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/season,
                      :rdf/type          :owl/Restriction}
                     {:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/DriverStandingType,
                                            :owl/onProperty
                                            :ergast/DriverStanding,
                                            :rdf/type :owl/Restriction}
                                           {:owl/allValuesFrom
                                            :ergast/ConstructorStandingType,
                                            :owl/onProperty
                                            :ergast/ConstructorStanding,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}]})

(def StandingsTable
  {:db/ident :ergast/StandingsTable,
   :rdf/type :owl/ObjectProperty})

(def StandingsTableType
  {:db/ident        :ergast/StandingsTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/StandingsListType,
                                            :owl/onProperty
                                            :ergast/StandingsList,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def Status
  {:db/ident :ergast/Status,
   :rdf/type :owl/ObjectProperty})

(def StatusTable
  {:db/ident :ergast/StatusTable,
   :rdf/type :owl/ObjectProperty})

(def StatusTableType
  {:db/ident        :ergast/StatusTableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/intersectionOf [{:owl/allValuesFrom
                                            :ergast/StatusType,
                                            :owl/onProperty :ergast/Status,
                                            :rdf/type :owl/Restriction}],
                      :rdf/type :owl/Class}
                     :ergast/TableType]})

(def StatusType
  {:db/ident        :ergast/StatusType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/count,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/statusId,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/statusId,
                      :rdf/type          :owl/Restriction}]})

(def TableType
  {:db/ident        :ergast/TableType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/statusId,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/position,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/grid,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/driverId,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/constructorId,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/circuitId,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/round,
                      :rdf/type          :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/season,
                      :rdf/type          :owl/Restriction}]})

(def Time
  {:db/ident :ergast/Time,
   :rdf/type :rdf/Property})

(def Timing
  {:db/ident :ergast/Timing,
   :rdf/type :owl/ObjectProperty})

(def TimingType
  {:db/ident        :ergast/TimingType,
   :rdf/type        :owl/Class,
   :rdfs/subClassOf [{:owl/minCardinality 1,
                      :owl/onProperty     :ergast/time,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/duration,
                      :owl/onProperty    :ergast/time,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/position,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/integer,
                      :owl/onProperty    :ergast/position,
                      :rdf/type          :owl/Restriction}
                     {:owl/minCardinality 1,
                      :owl/onProperty     :ergast/driverId,
                      :rdf/type           :owl/Restriction}
                     {:owl/allValuesFrom :xsd/string,
                      :owl/onProperty    :ergast/driverId,
                      :rdf/type          :owl/Restriction}]})

(def alt
  {:db/ident :ergast/alt,
   :rdf/type :owl/DatatypeProperty})

(def any
  {:db/ident :ergast/any,
   :rdf/type :owl/ObjectProperty})

(def circuitId
  {:db/ident :ergast/circuitId,
   :rdf/type :owl/DatatypeProperty})

(def constructorId
  {:db/ident :ergast/constructorId,
   :rdf/type :owl/DatatypeProperty})

(def count
  {:db/ident :ergast/count,
   :rdf/type :owl/DatatypeProperty})

(def driverId
  {:db/ident :ergast/driverId,
   :rdf/type :owl/DatatypeProperty})

(def duration
  {:db/ident :ergast/duration,
   :rdf/type :owl/DatatypeProperty})

(def grid
  {:db/ident :ergast/grid,
   :rdf/type :owl/DatatypeProperty})

(def lap
  {:db/ident :ergast/lap,
   :rdf/type :owl/DatatypeProperty})

(def lat
  {:db/ident :ergast/lat,
   :rdf/type :owl/DatatypeProperty})

(def limit
  {:db/ident :ergast/limit,
   :rdf/type :owl/DatatypeProperty})

(def long
  {:db/ident :ergast/long,
   :rdf/type :owl/DatatypeProperty})

(def millis
  {:db/ident :ergast/millis,
   :rdf/type :owl/DatatypeProperty})

(def number
  {:db/ident :ergast/number,
   :rdf/type :owl/DatatypeProperty})

(def offset
  {:db/ident :ergast/offset,
   :rdf/type :owl/DatatypeProperty})

(def points
  {:db/ident :ergast/points,
   :rdf/type :owl/DatatypeProperty})

(def position
  {:db/ident :ergast/position,
   :rdf/type :owl/DatatypeProperty})

(def rank
  {:db/ident :ergast/rank,
   :rdf/type :owl/DatatypeProperty})

(def round
  {:db/ident :ergast/round,
   :rdf/type :owl/DatatypeProperty})

(def season
  {:db/ident :ergast/season,
   :rdf/type :owl/DatatypeProperty})

(def series
  {:db/ident :ergast/series,
   :rdf/type :owl/DatatypeProperty})

(def statusId
  {:db/ident :ergast/statusId,
   :rdf/type :owl/DatatypeProperty})

(def stop
  {:db/ident :ergast/stop,
   :rdf/type :owl/DatatypeProperty})

(def time
  {:db/ident :ergast/time,
   :rdf/type :owl/DatatypeProperty})

(def total
  {:db/ident :ergast/total,
   :rdf/type :owl/DatatypeProperty})

(def units
  {:db/ident :ergast/units,
   :rdf/type :owl/DatatypeProperty})

(def url
  {:db/ident :ergast/url,
   :rdf/type :owl/DatatypeProperty})

(def wins
  {:db/ident :ergast/wins,
   :rdf/type :owl/DatatypeProperty})